/**
 * 政采单位初始化数据API
 * 根据文档导入广西政府采购单位和招标代理公司数据
 */

import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/db';
import { biddingPlatforms } from '@/db/bidding-platform-schema';
import { eq } from 'drizzle-orm';

// 初始化数据 - 来自文档《公共资源交易中心地址验证（2024 年）》和《广西政府采购单位百度地图坐标及开发对接说明》
const INITIAL_PLATFORMS = [
  // ==================== 区级官方平台 ====================
  {
    name: '广西壮族自治区公共资源交易中心',
    shortName: '区公共资源交易中心',
    type: 'provincial_official' as const,
    status: 'active' as const,
    address: '南宁市青秀区星湖路 22 号（开标楼 404 室）',
    phone: '0771-8600301',
    website: 'https://ggzy.jgswj.gxzf.gov.cn/',
    latitude: '22.816678',
    longitude: '108.327456',
    coordinatePrecision: '精准到开标楼 404 室',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: true,
    features: JSON.stringify([
      '全品类交易信息实时同步',
      '远程异地评标数据对接',
      'CA互认相关流程同步',
      '自治区级重大项目专属对接',
    ]),
    remarks: '加挂自治区政府采购中心牌子',
    verificationSource: '自治区公共资源交易中心官网',
    sortOrder: 1,
  },
  {
    name: '广西政府采购云平台（桂采云）',
    shortName: '桂采云',
    type: 'provincial_cloud' as const,
    status: 'active' as const,
    address: '南宁市青秀区星湖路 22 号广西政府采购中心综合楼 3 楼',
    phone: '95763',
    website: 'https://www.gxzfcg.gov.cn/',
    latitude: '22.816592',
    longitude: '108.327389',
    coordinatePrecision: '精准到综合楼 3 楼',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: false,
    features: JSON.stringify([
      '全流程电子化政府采购',
      '商城直采、竞价、框架协议、电子反拍',
      '供应商、采购人、代理机构注册信息同步',
      '政府采购政策实时更新',
    ]),
    remarks: '技术支持：政采云股份有限公司',
    verificationSource: '自治区公共资源交易中心公示',
    sortOrder: 2,
  },
  {
    name: '广西阳光采购服务平台',
    shortName: '阳光采购平台',
    type: 'state_owned' as const,
    status: 'active' as const,
    address: '南宁市青秀区枫林路 18 号广西国资交易中心',
    phone: '0771-5581051',
    website: 'https://ygcg.gxzf.gov.cn/',
    latitude: '22.823248',
    longitude: '108.412494',
    coordinatePrecision: '精准到国资交易中心主楼',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: true,
    features: JSON.stringify([
      '全区国企、区市直属国企采购信息',
      '物资、服务、工程招标+竞价+直采',
      '入驻企业信息、项目数据同步',
      '电子合同、全程监管信息同步',
    ]),
    remarks: '标准化场地坐标：经度 108.412494，纬度 22.823248',
    verificationSource: '平台官网',
    sortOrder: 3,
  },
  
  // ==================== 地市公共资源交易中心 ====================
  {
    name: '南宁市公共资源交易中心',
    shortName: '南宁交易中心',
    type: 'city_center' as const,
    status: 'active' as const,
    address: '南宁市良庆区玉洞大道 33 号南宁市民中心 9-11 层',
    phone: '0771-4955091',
    website: 'https://ggzy.nanning.gov.cn/',
    latitude: '22.766857',
    longitude: '108.347982',
    coordinatePrecision: '精准到市民中心 9-11 层',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: true,
    features: JSON.stringify(['市级政府采购', '工程交易业务', '开标直播同步']),
    remarks: '主要办理市级政府采购、工程交易业务',
    verificationSource: '南宁市公共资源交易中心简介',
    sortOrder: 10,
  },
  {
    name: '柳州市公共资源交易中心',
    shortName: '柳州交易中心',
    type: 'city_center' as const,
    status: 'active' as const,
    address: '柳州市城中区文昌路 66 号文昌综合楼 9 楼',
    phone: '0772-2102231',
    website: 'https://ggzy.liuzhou.gov.cn/',
    latitude: '24.307865',
    longitude: '109.405689',
    coordinatePrecision: '精准到文昌综合楼 9 楼',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: true,
    features: JSON.stringify(['桂中地区核心交易平台']),
    remarks: '桂中地区核心交易平台',
    verificationSource: '柳州市公共资源交易中心举报指南',
    sortOrder: 11,
  },
  {
    name: '桂林市公共资源交易中心',
    shortName: '桂林交易中心',
    type: 'city_center' as const,
    status: 'active' as const,
    address: '桂林市临桂区西城中路 69 号创业大厦西辅楼 4-5 楼',
    phone: '0773-5625165',
    website: 'https://ggzy.guilin.gov.cn/',
    latitude: '25.179876',
    longitude: '110.298765',
    coordinatePrecision: '精准到创业大厦西辅楼 4-5 楼',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: true,
    features: JSON.stringify(['桂北地区最大交易平台']),
    remarks: '桂北地区最大交易平台',
    verificationSource: '桂林市公共资源交易平台信息化建设公示',
    sortOrder: 12,
  },
  {
    name: '梧州市公共资源交易中心',
    shortName: '梧州交易中心',
    type: 'city_center' as const,
    status: 'active' as const,
    address: '梧州市长洲区三龙大道 72 号红岭大厦 8 楼',
    phone: '0774-3828336',
    website: 'https://ggzy.wuzhou.gov.cn/',
    latitude: '23.487654',
    longitude: '111.345678',
    coordinatePrecision: '精准到红岭大厦 8 楼',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: false,
    features: JSON.stringify(['涵盖工程、政府采购、产权交易']),
    verificationSource: '梧州市行政审批局机构职能公示',
    sortOrder: 13,
  },
  {
    name: '北海市公共资源交易中心',
    shortName: '北海交易中心',
    type: 'city_center' as const,
    status: 'active' as const,
    address: '北海市海城区北海大道 177 号北海市政务服务中心 3 楼',
    phone: '0779-3960811',
    website: 'https://ggzy.beihai.gov.cn/',
    latitude: '21.489876',
    longitude: '109.123456',
    coordinatePrecision: '精准到政务服务中心 3 楼',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: true,
    features: JSON.stringify(['沿海地区特色交易服务']),
    verificationSource: '北海市公共资源交易中心官网',
    sortOrder: 14,
  },
  {
    name: '防城港市公共资源交易中心',
    shortName: '防城港交易中心',
    type: 'city_center' as const,
    status: 'active' as const,
    address: '防城港市迎宾路红树林大厦东塔 2 楼、6 楼及 7 楼',
    phone: '0770-2881188',
    website: 'https://ggzy.fcgs.gov.cn/',
    latitude: '21.678901',
    longitude: '108.345678',
    coordinatePrecision: '精准到红树林大厦东塔',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: true,
    features: JSON.stringify(['建筑面积约 1300㎡', '含开标区、评标区']),
    verificationSource: '全国公共资源交易平台(防城港)',
    sortOrder: 15,
  },
  {
    name: '钦州市公共资源交易中心',
    shortName: '钦州交易中心',
    type: 'city_center' as const,
    status: 'active' as const,
    address: '钦州市钦南区金海湾东大街 8 号市政务服务中心 3 楼行政办公区',
    phone: '0777-2588336',
    website: 'https://ggzy.qinzhou.gov.cn/',
    latitude: '21.956789',
    longitude: '108.678901',
    coordinatePrecision: '精准到政务服务中心 3 楼办公区',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: true,
    features: JSON.stringify(['支持北部湾经济区项目交易']),
    verificationSource: '钦州市人民政府代管机构公示',
    sortOrder: 16,
  },
  {
    name: '贵港市公共资源交易中心',
    shortName: '贵港交易中心',
    type: 'city_center' as const,
    status: 'active' as const,
    address: '贵港市港北区金田路水利大厦 1-4 楼',
    phone: '0775-4556923',
    website: 'https://ggzy.jgswj.gxgg.gov.cn/',
    latitude: '23.123456',
    longitude: '109.567890',
    coordinatePrecision: '精准到水利大厦 1-4 楼',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: false,
    features: JSON.stringify(['桂东南地区交易枢纽']),
    verificationSource: '贵港市人民政府机构职能公示',
    sortOrder: 17,
  },
  {
    name: '玉林市公共资源交易中心',
    shortName: '玉林交易中心',
    type: 'city_center' as const,
    status: 'active' as const,
    address: '玉林市玉东新区秀水路 2 号玉林市政务服务中心 5 楼',
    phone: '0775-2680181',
    website: 'https://ggzy.yulin.gov.cn/',
    latitude: '22.634567',
    longitude: '110.123456',
    coordinatePrecision: '精准到政务服务中心 5 楼',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: true,
    features: JSON.stringify(['货物、服务、工程类交易全覆盖']),
    verificationSource: '玉林市政府招标公示',
    sortOrder: 18,
  },
  {
    name: '百色市公共资源交易中心',
    shortName: '百色交易中心',
    type: 'city_center' as const,
    status: 'active' as const,
    address: '百色市右江区园博路政务服务中心 3 楼',
    phone: '0776-2382333',
    website: 'https://ggzy.baise.gov.cn/',
    latitude: '23.901234',
    longitude: '106.678901',
    coordinatePrecision: '精准到政务服务中心 3 楼',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: true,
    features: JSON.stringify(['含阳光采购百色开评标场地']),
    verificationSource: '百色市人民政府门户网站',
    sortOrder: 19,
  },
  {
    name: '贺州市公共资源交易中心',
    shortName: '贺州交易中心',
    type: 'city_center' as const,
    status: 'active' as const,
    address: '贺州市八步区太白西路 161 号政务服务中心 4 楼 C 区及东侧附属楼',
    phone: '0774-5268001',
    website: 'https://ggzy.hezhou.gov.cn/',
    latitude: '24.456789',
    longitude: '111.567890',
    coordinatePrecision: '精准到政务服务中心 4 楼 C 区',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: false,
    features: JSON.stringify(['桂东地区交易平台']),
    verificationSource: '贺州市人民政府门户网站',
    sortOrder: 20,
  },
  {
    name: '河池市公共资源交易中心',
    shortName: '河池交易中心',
    type: 'city_center' as const,
    status: 'active' as const,
    address: '河池市金城江区江湾路 2 号 6 楼 617 室',
    phone: '0778-2306908',
    website: 'https://ggzy.hechi.gov.cn/',
    latitude: '24.789012',
    longitude: '108.012345',
    coordinatePrecision: '精准到江湾路 2 号 6 楼 617 室',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: false,
    features: JSON.stringify(['桂西北山区项目交易服务']),
    verificationSource: '比地招标网官方注册信息',
    sortOrder: 21,
  },
  {
    name: '来宾市公共资源交易中心',
    shortName: '来宾交易中心',
    type: 'city_center' as const,
    status: 'active' as const,
    address: '来宾市兴宾区宾城路西 139 号政务服务中心 3 楼',
    phone: '0772-4278508',
    website: 'https://ggzy.laibin.gov.cn/',
    latitude: '23.765432',
    longitude: '109.234567',
    coordinatePrecision: '精准到政务服务中心 3 楼',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: true,
    features: JSON.stringify(['支持桂中地区跨市项目']),
    verificationSource: '来宾市公共资源交易中心官网公示',
    sortOrder: 22,
  },
  {
    name: '崇左市公共资源交易中心',
    shortName: '崇左交易中心',
    type: 'city_center' as const,
    status: 'active' as const,
    address: '崇左市江州区石景林路 9 号政务服务中心 5 楼',
    phone: '0771-7968336',
    website: 'https://ggzy.chongzuo.gov.cn/',
    latitude: '22.456789',
    longitude: '107.345678',
    coordinatePrecision: '精准到政务服务中心 5 楼',
    supportOnlineBid: true,
    supportCaLogin: true,
    supportLiveStream: true,
    features: JSON.stringify(['边境地区特色交易服务']),
    verificationSource: '崇左市公共资源交易中心官网公示',
    sortOrder: 23,
  },
  
  // ==================== 招标代理公司 ====================
  {
    name: '云之龙咨询集团有限公司',
    shortName: '云之龙',
    type: 'agent_company' as const,
    status: 'active' as const,
    address: '南宁市青秀区中泰路 11 号北部湾大厦 19 楼',
    phone: '0771-2851811',
    website: 'https://www.ylzbtb.com/',
    latitude: '22.801234',
    longitude: '108.356789',
    coordinatePrecision: '精准到北部湾大厦 19 楼',
    supportOnlineBid: true,
    supportCaLogin: false,
    supportLiveStream: false,
    features: JSON.stringify([
      '2025广西代理TOP2',
      '全区14地市设分公司',
      '政府采购常年第一',
      '专人答疑通道',
    ]),
    remarks: '原云龙招标，全区14地市分公司',
    verificationSource: '公司官网联系我们',
    sortOrder: 30,
  },
  {
    name: '广西机电设备招标有限公司',
    shortName: '机电设备招标',
    type: 'agent_company' as const,
    status: 'active' as const,
    address: '南宁市青秀区金湖路 63 号金源 CBD 现代城 7 楼',
    phone: '0771-2808960',
    website: 'https://www.gxbidding.com/',
    latitude: '22.812345',
    longitude: '108.357890',
    coordinatePrecision: '精准到金源 CBD 现代城 7 楼',
    supportOnlineBid: true,
    supportCaLogin: false,
    supportLiveStream: false,
    features: JSON.stringify([
      '2025广西代理TOP3',
      '国企',
      '多甲级资质',
      '医疗、高校、交通、烟草项目优势',
    ]),
    verificationSource: '公司官网联系我们',
    sortOrder: 31,
  },
  {
    name: '广西交投宏冠工程咨询有限公司',
    shortName: '交投宏冠',
    type: 'agent_company' as const,
    status: 'active' as const,
    address: '南宁市青秀区合作路 6 号五洲国际 C 座 23 楼',
    phone: '0771-4735300',
    website: 'https://www.hgzb.com.cn/',
    latitude: '22.803456',
    longitude: '108.378901',
    coordinatePrecision: '精准到五洲国际 C 座 23 楼',
    supportOnlineBid: true,
    supportCaLogin: false,
    supportLiveStream: false,
    features: JSON.stringify([
      '2025广西代理TOP1',
      '国企',
      '交通工程类项目龙头',
      '公路、水运、市政、房建',
    ]),
    verificationSource: '公司官网联系我们',
    sortOrder: 32,
  },
  {
    name: '广西国盛招标有限公司',
    shortName: '国盛招标',
    type: 'agent_company' as const,
    status: 'active' as const,
    address: '南宁市青秀区朱槿路 10 号新加坡园区星岛国际 3 楼',
    phone: '0771-5828119',
    website: 'https://www.gxgszb.com/',
    latitude: '22.804567',
    longitude: '108.389012',
    coordinatePrecision: '精准到星岛国际 3 楼',
    supportOnlineBid: true,
    supportCaLogin: false,
    supportLiveStream: false,
    features: JSON.stringify([
      '全国百强',
      '广西民营10强',
      '多资质',
      '中小企业项目特色',
    ]),
    verificationSource: '公司官网联系我们',
    sortOrder: 33,
  },
  {
    name: '广西中信恒泰工程顾问有限公司',
    shortName: '中信恒泰',
    type: 'agent_company' as const,
    status: 'active' as const,
    address: '南宁市青秀区云景路 69 号南宁轨道大厦 B 座 15 楼',
    phone: '0771-5775551',
    website: 'https://www.gxzxht.com/',
    latitude: '22.823456',
    longitude: '108.367890',
    coordinatePrecision: '精准到南宁轨道大厦 B 座 15 楼',
    supportOnlineBid: true,
    supportCaLogin: false,
    supportLiveStream: false,
    features: JSON.stringify([
      '2025广西代理TOP10',
      '全过程工程咨询龙头',
      '大型房建/市政项目优势',
    ]),
    verificationSource: '公司官网联系我们',
    sortOrder: 34,
  },
  {
    name: '广西建通工程咨询有限责任公司',
    shortName: '建通咨询',
    type: 'agent_company' as const,
    status: 'active' as const,
    address: '南宁市青秀区佛子岭路 18 号德利东盟国际文化广场 B3 栋 10 楼',
    phone: '0771-5675896',
    website: 'https://www.gxjtzx.com/',
    latitude: '22.824567',
    longitude: '108.378901',
    coordinatePrecision: '精准到德利东盟国际文化广场 B3 栋 10 楼',
    supportOnlineBid: true,
    supportCaLogin: false,
    supportLiveStream: false,
    features: JSON.stringify([
      '2025广西代理TOP9',
      '桂西/南宁强企',
    ]),
    verificationSource: '公司官网联系我们',
    sortOrder: 35,
  },
  {
    name: '广西同泽工程项目管理股份有限公司',
    shortName: '同泽工程',
    type: 'agent_company' as const,
    status: 'active' as const,
    address: '南宁市五象总部基地广东大厦 18 楼',
    phone: '0771-5285609',
    website: 'https://www.gxtzzx.com/',
    latitude: '22.756789',
    longitude: '108.389012',
    coordinatePrecision: '精准到广东大厦 18 楼',
    supportOnlineBid: true,
    supportCaLogin: false,
    supportLiveStream: false,
    features: JSON.stringify([
      '全区性综合代理',
      '多资质',
      '桂采云无缝对接',
    ]),
    verificationSource: '公司官网联系我们',
    sortOrder: 36,
  },
  {
    name: '广西国泰招标咨询有限公司',
    shortName: '国泰招标',
    type: 'agent_company' as const,
    status: 'active' as const,
    address: '南宁市青秀区民族大道 141 号中鼎万象东方 C 座 10 楼',
    phone: '0771-2023559',
    website: 'https://www.gtzbzx.com/',
    latitude: '22.815678',
    longitude: '108.345678',
    coordinatePrecision: '精准到中鼎万象东方 C 座 10 楼',
    supportOnlineBid: true,
    supportCaLogin: false,
    supportLiveStream: false,
    features: JSON.stringify([
      '南宁老牌甲级',
      '多资质',
      '政法、教育、医疗项目稳定',
    ]),
    verificationSource: '公司官网联系我们',
    sortOrder: 37,
  },
  {
    name: '广西华东招标有限公司',
    shortName: '华东招标',
    type: 'agent_company' as const,
    status: 'active' as const,
    address: '南宁市青秀区东葛路 118 号南宁青秀万达广场西 3 栋 15 楼',
    phone: '0771-5825853',
    website: 'https://www.gxhdzb.com/',
    latitude: '22.816789',
    longitude: '108.356789',
    coordinatePrecision: '精准到青秀万达广场西 3 栋 15 楼',
    supportOnlineBid: true,
    supportCaLogin: false,
    supportLiveStream: false,
    features: JSON.stringify([
      '区级采购人入库代理',
      '综合类',
    ]),
    verificationSource: '公司官网联系我们',
    sortOrder: 38,
  },
  {
    name: '广西天翔工程管理有限公司',
    shortName: '天翔管理',
    type: 'agent_company' as const,
    status: 'active' as const,
    address: '南宁市西乡塘区大学东路 160 号瑞士花园翠湖苑 2 栋 2 单元',
    phone: '0771-3898389',
    website: 'https://www.gx-txzb.com/',
    latitude: '22.837890',
    longitude: '108.323456',
    coordinatePrecision: '精准到瑞士花园翠湖苑 2 栋 2 单元',
    supportOnlineBid: true,
    supportCaLogin: false,
    supportLiveStream: false,
    features: JSON.stringify([
      '南宁本地新锐',
      '小额项目响应快',
      '政府采购+造价+标书代写',
    ]),
    verificationSource: '公司官网联系我们',
    sortOrder: 39,
  },
];

// ============================================
// POST - 初始化政采单位数据
// ============================================

export async function POST(request: NextRequest) {
  try {
    let body = { force: false };
    try {
      const text = await request.text();
      if (text) {
        body = JSON.parse(text);
      }
    } catch {
      // 如果解析失败，使用默认值
    }
    const force = body?.force === true; // 是否强制覆盖
    
    let inserted = 0;
    let updated = 0;
    let skipped = 0;
    
    for (const platform of INITIAL_PLATFORMS) {
      // 检查是否已存在
      const existing = await db
        .select()
        .from(biddingPlatforms)
        .where(eq(biddingPlatforms.name, platform.name))
        .limit(1);
      
      if (existing.length > 0) {
        if (force) {
          // 强制更新
          await db
            .update(biddingPlatforms)
            .set({
              ...platform,
              updatedAt: new Date(),
            })
            .where(eq(biddingPlatforms.id, existing[0].id));
          updated++;
        } else {
          skipped++;
        }
      } else {
        // 新增
        await db.insert(biddingPlatforms).values(platform);
        inserted++;
      }
    }
    
    return NextResponse.json({
      success: true,
      message: `初始化完成：新增 ${inserted} 条，更新 ${updated} 条，跳过 ${skipped} 条`,
      stats: { inserted, updated, skipped, total: INITIAL_PLATFORMS.length },
    });
  } catch (error) {
    console.error('Failed to initialize platforms:', error);
    return NextResponse.json(
      { success: false, error: '初始化失败' },
      { status: 500 }
    );
  }
}
