// Auto-generated by scripts/generate-tender-center-dto-zod.py
// DO NOT EDIT MANUALLY.

import { z } from 'zod';

export const tenderCenterDtoContracts = {
  getBatchesBatchIdContract: {
    method: 'GET',
    path: '/api/tender-center/batches/[batchId]',
    request: {
      path: z.object({
        batchId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getBatchesBatchIdAiTasksContract: {
    method: 'GET',
    path: '/api/tender-center/batches/[batchId]/ai-tasks',
    request: {
      path: z.object({
        batchId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getBatchesBatchIdConfidenceContract: {
    method: 'GET',
    path: '/api/tender-center/batches/[batchId]/confidence',
    request: {
      path: z.object({
        batchId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getBatchesBatchIdRuleHitsContract: {
    method: 'GET',
    path: '/api/tender-center/batches/[batchId]/rule-hits',
    request: {
      path: z.object({
        batchId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getChangeLogsContract: {
    method: 'GET',
    path: '/api/tender-center/change-logs',
    request: {
      path: z.object({}),
      query: z.object({
        pageNo: z.number().optional(),
        pageSize: z.number().optional(),
      }),
      body: z.object({}),
    },
  },
  postClarificationsClarificationIdConfirmContract: {
    method: 'POST',
    path: '/api/tender-center/clarifications/[clarificationId]/confirm',
    request: {
      path: z.object({
        clarificationId: z.string(),
      }),
      query: z.object({}),
      body: z.object({
        comment: z.string().optional(),
        note: z.string().optional(),
      }),
    },
  },
  getConflictsConflictIdContract: {
    method: 'GET',
    path: '/api/tender-center/conflicts/[conflictId]',
    request: {
      path: z.object({
        conflictId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  postConflictsConflictIdResolveContract: {
    method: 'POST',
    path: '/api/tender-center/conflicts/[conflictId]/resolve',
    request: {
      path: z.object({
        conflictId: z.string(),
      }),
      query: z.object({}),
      body: z.object({
        note: z.string().optional(),
        resolution: z.string().optional(),
      }),
    },
  },
  getFrameworkNodeIdContract: {
    method: 'GET',
    path: '/api/tender-center/framework/[nodeId]',
    request: {
      path: z.object({
        nodeId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsContract: {
    method: 'GET',
    path: '/api/tender-center/projects',
    request: {
      path: z.object({}),
      query: z.object({
        keyword: z.string().optional(),
        sortBy: z.string().optional(),
        sortOrder: z.string().optional(),
        status: z.array(z.string()).optional(),
      }),
      body: z.object({
        budget: z.string().optional(),
        code: z.string(),
        departmentId: z.string(),
        description: z.string().optional(),
        industry: z.string().optional(),
        name: z.string(),
        openBidDate: z.string().optional(),
        ownerId: z.string(),
        publishDate: z.string().optional(),
        questionDeadline: z.string().optional(),
        region: z.string().optional(),
        registerDeadline: z.string().optional(),
        submissionDeadline: z.string().optional(),
        tags: z.string().optional(),
        tenderAgent: z.string().optional(),
        tenderCode: z.string().optional(),
        tenderMethod: z.string().optional(),
        tenderOrganization: z.string().optional(),
        type: z.string().optional(),
      }),
    },
  },
  postProjectsContract: {
    method: 'POST',
    path: '/api/tender-center/projects',
    request: {
      path: z.object({}),
      query: z.object({
        keyword: z.string().optional(),
        sortBy: z.string().optional(),
        sortOrder: z.string().optional(),
        status: z.array(z.string()).optional(),
      }),
      body: z.object({
        budget: z.string().optional(),
        code: z.string(),
        departmentId: z.string(),
        description: z.string().optional(),
        industry: z.string().optional(),
        name: z.string(),
        openBidDate: z.string().optional(),
        ownerId: z.string(),
        publishDate: z.string().optional(),
        questionDeadline: z.string().optional(),
        region: z.string().optional(),
        registerDeadline: z.string().optional(),
        submissionDeadline: z.string().optional(),
        tags: z.string().optional(),
        tenderAgent: z.string().optional(),
        tenderCode: z.string().optional(),
        tenderMethod: z.string().optional(),
        tenderOrganization: z.string().optional(),
        type: z.string().optional(),
      }),
    },
  },
  getProjectsProjectIdContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]',
    request: {
      path: z.object({
        projectId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  postProjectsProjectIdUploadContract: {
    method: 'POST',
    path: '/api/tender-center/projects/[projectId]/upload',
    request: {
      path: z.object({
        projectId: z.string(),
      }),
      query: z.object({}),
      body: z.object({
        documentExt: z.string().optional(),
        documentMd5: z.string().optional(),
        documentName: z.string().optional(),
        documentPageCount: z.string().optional(),
        documentSize: z.string().optional(),
        documentUrl: z.string().optional(),
      }),
    },
  },
  getProjectsProjectIdVersionsContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions',
    request: {
      path: z.object({
        projectId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdBatchesContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/batches',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdClarificationsContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/clarifications',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdConflictsContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/conflicts',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdExportContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/export',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdFrameworkContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/framework',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdMaterialViewContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/material-view',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdMaterialsContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/materials',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdMoneyTermsContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/money-terms',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdOverviewContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/overview',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdPagesContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/pages',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  postProjectsProjectIdVersionsVersionIdParseContract: {
    method: 'POST',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/parse',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdRequirementsContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/requirements',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdResponseTasksContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/response-tasks',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdReviewsContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/reviews',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdRiskViewContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/risk-view',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdRisksContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/risks',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdScoringItemsContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/scoring-items',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdScoringSchemesContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/scoring-schemes',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdSectionsContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/sections',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdSegmentsContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/segments',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdSnapshotsContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/snapshots',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({
        name: z.string().optional(),
        note: z.string().optional(),
      }),
    },
  },
  postProjectsProjectIdVersionsVersionIdSnapshotsContract: {
    method: 'POST',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/snapshots',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({
        name: z.string().optional(),
        note: z.string().optional(),
      }),
    },
  },
  getProjectsProjectIdVersionsVersionIdSubmissionRequirementsContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/submission-requirements',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdTechnicalGroupsContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/technical-groups',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdTechnicalItemsContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/technical-items',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdTemplateViewContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/template-view',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdTemplatesContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/templates',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getProjectsProjectIdVersionsVersionIdTimeNodesContract: {
    method: 'GET',
    path: '/api/tender-center/projects/[projectId]/versions/[versionId]/time-nodes',
    request: {
      path: z.object({
        projectId: z.string(),
        versionId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getRequirementsRequirementIdContract: {
    method: 'GET',
    path: '/api/tender-center/requirements/[requirementId]',
    request: {
      path: z.object({
        requirementId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  postReviewsContract: {
    method: 'POST',
    path: '/api/tender-center/reviews',
    request: {
      path: z.object({}),
      query: z.object({}),
      body: z.object({
        assignedReviewerId: z.number().optional(),
        note: z.string().optional(),
        projectId: z.string().optional(),
        versionId: z.string().optional(),
      }),
    },
  },
  postReviewsReviewTaskIdSubmitContract: {
    method: 'POST',
    path: '/api/tender-center/reviews/[reviewTaskId]/submit',
    request: {
      path: z.object({
        reviewTaskId: z.string(),
      }),
      query: z.object({}),
      body: z.object({
        comment: z.string().optional(),
        decision: z.string().optional(),
        reviewAccuracy: z.number().optional(),
      }),
    },
  },
  getRisksRiskIdContract: {
    method: 'GET',
    path: '/api/tender-center/risks/[riskId]',
    request: {
      path: z.object({
        riskId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  postRisksRiskIdCloseContract: {
    method: 'POST',
    path: '/api/tender-center/risks/[riskId]/close',
    request: {
      path: z.object({
        riskId: z.string(),
      }),
      query: z.object({}),
      body: z.object({
        comment: z.string().optional(),
        note: z.string().optional(),
      }),
    },
  },
  getSnapshotsSnapshotIdContract: {
    method: 'GET',
    path: '/api/tender-center/snapshots/[snapshotId]',
    request: {
      path: z.object({
        snapshotId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getSourceSegmentsSegmentIdContract: {
    method: 'GET',
    path: '/api/tender-center/source-segments/[segmentId]',
    request: {
      path: z.object({
        segmentId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getTemplatesTemplateIdContract: {
    method: 'GET',
    path: '/api/tender-center/templates/[templateId]',
    request: {
      path: z.object({
        templateId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
  getTemplatesTemplateIdVariablesContract: {
    method: 'GET',
    path: '/api/tender-center/templates/[templateId]/variables',
    request: {
      path: z.object({
        templateId: z.string(),
      }),
      query: z.object({}),
      body: z.object({}),
    },
  },
} as const;

export type TenderCenterDtoContractMap = typeof tenderCenterDtoContracts;
export type TenderCenterDtoContractKey = keyof TenderCenterDtoContractMap;

export type TenderCenterDtoRequestPath<T extends TenderCenterDtoContractKey> = z.infer<
  TenderCenterDtoContractMap[T]['request']['path']
>;

export type TenderCenterDtoRequestQuery<T extends TenderCenterDtoContractKey> = z.infer<
  TenderCenterDtoContractMap[T]['request']['query']
>;

export type TenderCenterDtoRequestBody<T extends TenderCenterDtoContractKey> = z.infer<
  TenderCenterDtoContractMap[T]['request']['body']
>;
