#!/usr/bin/env python3
"""
W4-002: 从 W2 字段契约快照生成 Zod DTO，并支持 CI 漂移校验。
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


def to_identifier(method: str, path: str) -> str:
    normalized = path.replace("/api/tender-center/", "")
    normalized = re.sub(r"\[([^\]]+)\]", r"\1", normalized)
    parts = re.split(r"[^A-Za-z0-9]+", normalized)
    parts = [p for p in parts if p]
    camel = "".join(part[0].upper() + part[1:] for part in parts)
    return f"{method.lower()}{camel}Contract"


def esc(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def field_to_zod(field: dict[str, Any]) -> str:
    t = field.get("type", "unknown")
    enum_values = field.get("enum")
    required = bool(field.get("required", False))

    if enum_values:
        vals = ", ".join(f"'{esc(str(v))}'" for v in enum_values)
        base = f"z.enum([{vals}] as const)"
    elif t == "string":
        base = "z.string()"
    elif t == "number":
        base = "z.number()"
    elif t == "boolean":
        base = "z.boolean()"
    elif t == "array<string>":
        base = "z.array(z.string())"
    elif t == "date":
        # API 里日期目前以字符串传输，保持兼容
        base = "z.string()"
    else:
        base = "z.unknown()"

    if not required:
        return f"{base}.optional()"
    return base


def object_schema(fields: dict[str, dict[str, Any]]) -> str:
    if not fields:
        return "z.object({})"
    lines = ["z.object({"]
    for key in sorted(fields.keys()):
        lines.append(f"    {key}: {field_to_zod(fields[key])},")
    lines.append("  })")
    return "\n".join(lines)


def generate_source(snapshot: dict[str, Any]) -> str:
    contracts: list[dict[str, Any]] = snapshot.get("contracts", [])
    contracts = [
        c for c in contracts if c.get("exists") and c.get("methodImplemented")
    ]
    contracts.sort(key=lambda c: (c.get("path", ""), c.get("method", "")))

    lines: list[str] = []
    lines.extend(
        [
            "// Auto-generated by scripts/generate-tender-center-dto-zod.py",
            "// DO NOT EDIT MANUALLY.",
            "",
            "import { z } from 'zod';",
            "",
            "export const tenderCenterDtoContracts = {",
        ]
    )

    for contract in contracts:
        method = str(contract["method"]).upper()
        path = str(contract["path"])
        name = to_identifier(method, path)
        req = contract.get("request", {})
        path_schema = object_schema(req.get("path", {}))
        query_schema = object_schema(req.get("query", {}))
        body_schema = object_schema(req.get("body", {}))
        lines.extend(
            [
                f"  {name}: {{",
                f"    method: '{method}',",
                f"    path: '{path}',",
                f"    request: {{",
                f"      path: {path_schema},",
                f"      query: {query_schema},",
                f"      body: {body_schema},",
                f"    }},",
                "  },",
            ]
        )

    lines.extend(
        [
            "} as const;",
            "",
            "export type TenderCenterDtoContractMap = typeof tenderCenterDtoContracts;",
            "export type TenderCenterDtoContractKey = keyof TenderCenterDtoContractMap;",
            "",
            "export type TenderCenterDtoRequestPath<T extends TenderCenterDtoContractKey> = z.infer<",
            "  TenderCenterDtoContractMap[T]['request']['path']",
            ">;",
            "",
            "export type TenderCenterDtoRequestQuery<T extends TenderCenterDtoContractKey> = z.infer<",
            "  TenderCenterDtoContractMap[T]['request']['query']",
            ">;",
            "",
            "export type TenderCenterDtoRequestBody<T extends TenderCenterDtoContractKey> = z.infer<",
            "  TenderCenterDtoContractMap[T]['request']['body']",
            ">;",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    if not args.write and not args.check:
        parser.error("must specify --write or --check")

    repo = Path(__file__).resolve().parents[1]
    snapshot_path = repo / "contracts" / "tender-center-w2-field-contract.json"
    output_path = repo / "src" / "app" / "api" / "tender-center" / "_dto-contract.zod.ts"

    if not snapshot_path.is_file():
        print(f"Snapshot not found: {snapshot_path}", file=sys.stderr)
        return 2

    snapshot = json.loads(snapshot_path.read_text(encoding="utf-8"))
    content = generate_source(snapshot) + "\n"

    if args.write:
        output_path.write_text(content, encoding="utf-8")
        print(f"Wrote {output_path.relative_to(repo)}")
        return 0

    if not output_path.is_file():
        print("Generated DTO contract file missing. Run --write first.", file=sys.stderr)
        return 2

    existing = output_path.read_text(encoding="utf-8")
    if existing == content:
        print("W4-002 DTO Zod contract drift check passed.")
        return 0

    print("W4-002 DTO Zod contract drift detected.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
